chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register_user, name="register"),
    path("accounts/login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("chat/", views.chat, name="chat"),
    path("chat/<slug:other_username>/", views.room, name="room"),
    path("user_status/<int:user_pk>/", views.user_status, name="user_status")
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('', include("chat.urls", namespace='chat')),
    path('friend/', include("friend.urls", namespace='friend')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

friend/urls.py
from django.urls import path

from . import views

app_name = 'friend'

urlpatterns = [
    path("search/", views.search_friend, name="search_friend"),
    path("add/<slug:nickname>/", views.add_friend, name="add_friend"),
]

messanger/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from messanger import settings

urlpatterns = [
    path('', include("chat.urls", namespace='chat')),
    path('friend/', include("friend.urls", namespace='friend')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

chat/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models

from chat.validators import nickname_validator


class User(AbstractUser):
    username = models.CharField(
        verbose_name='Псевдонім',
        max_length=50,
        unique=True,
        validators=[nickname_validator],
    )
    # nickname = models.CharField(verbose_name='Псевдонім', max_length=50, unique=True, validators=[nickname_validator])
    avatar = models.ImageField(verbose_name='Фото профілю', upload_to='images/avatars/', blank=True, default='images/avatars/default_avatar.png')
    friends = models.ManyToManyField('self')

    # USERNAME_FIELD = "nickname"


class Conversation(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    conversation = models.ForeignKey(
        Conversation, on_delete=models.CASCADE, related_name="messages"
    )
    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="messages_from_me"
    )
    to_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="messages_to_me"
    )
    content = models.CharField(max_length=512)
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"From {self.from_user.username} to {self.to_user.username}: {self.content} [{self.timestamp}]"

friend/models.py
from django.db import models

# Create your models here.

chat/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class RegisterUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'avatar')

chat/views.py
import json
import redis

from django.contrib.auth import logout, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.safestring import mark_safe

from chat.forms import RegisterUserForm
from config import settings

User = get_user_model()

redis_instance = redis.StrictRedis(host=settings.REDIS_HOST,
                                  port=settings.REDIS_PORT, db=0)
def index(request):
    if request.user.is_authenticated:
        return redirect('chat:chat')
    else:
        return render(request, "chat/index.html")


@login_required
def chat(request):
    return render(request, 'chat/chat.html')


@login_required
def room(request, other_username):
    other_user = get_object_or_404(User, username=other_username)
    room_name = "_".join(sorted([request.user.username, other_user.username]))
    context = {
        "other_user": other_user,
        "room_name": room_name
    }
    return render(request, "chat/room.html", context)


def register_user(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            redis_instance.set(user.pk, 'Offline')
            return redirect('chat:chat')
    else:
        form = RegisterUserForm()
    return render(request, 'chat/account/register.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('chat:chat')
    else:
        form = AuthenticationForm()
    return render(request, 'chat/account/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('chat:index')


def user_status(request, user_pk):
    status = redis_instance.get(user_pk)
    if status:
        status = status.decode('utf-8')
    else:
        status = 'Offline'
    return JsonResponse({'status': status}, safe=False)

friend/views.py
import json

from django.contrib.auth import get_user_model
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse

from config.settings import MEDIA_URL

User = get_user_model()


def search_friend(request):
    if request.method == 'GET':
        nickname = request.GET.get("nickname", '#')
        users = User.objects.filter(Q(username__icontains=nickname) & ~Q(username=request.user.username)).values('username', 'avatar')

        user_list = []
        for user in users:
            user_dict = {
                'username': user['username'],
                'avatar': MEDIA_URL + user['avatar'],
                'chat_room': reverse('chat:room', args=[user['username']])
            }
            user_list.append(user_dict)

        return JsonResponse({'users': user_list}, safe=False)


def add_friend(request, nickname):
    friend = get_object_or_404(User, username=nickname)
    request.user.friends.add(friend)
    return JsonResponse({'message': 'Додано'}, safe=False)

templates/chat/account/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Simple Web Chat</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<div class="container">
    <h1>SWC - Simple Web Chat</h1>
    <div class="form">
        <form action="{% url 'chat:login' %}" method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for field in form %}
                <div class="form-input">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}{% if field.field.required %} *{% endif %}:</label>
                    <br>
                    {{ field }}
                    <div class="form-error">{{ field.errors }}</div>
                </div>
            {% endfor %}
            <input class="form-button" type="submit" value="Увійти">
{#            <button type="submit">Увійти</button>#}
        </form>
    </div>
</div>
</body>
</html>

templates/chat/account/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Simple Web Chat</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<div class="container">
    <h1>SWC - Simple Web Chat</h1>
    <div class="form">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for field in form %}
                <div class="form-input">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}{% if field.field.required %} *{% endif %}:</label>
                    <br>
                    {{ field }}
                    <div class="form-error">{{ field.errors }}</div>
                </div>
            {% endfor %}
            <input class="form-button" type="submit" value="Зареєструватись">
        </form>
    </div>
</div>
</body>
</html>

templates/chat/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
<div class="container app">
    <div class="row app-one">
        <div class="col-sm-4 side">
            <div class="side-one">
                <div class="row heading">
                    <div class="col-sm-3 col-xs-3 heading-avatar">
                        <div class="heading-avatar-icon">
                            <img src="{{ user.avatar.url }}">
                        </div>
                    </div>
                    {#                    <div class="col-sm-1 col-xs-1 heading-dot pull-right" id="actions-dropdown">#}

                        <a href="{% url 'chat:logout' %}">Вийти</a>

                    {#                    </div>#}
                    <a href="{% url 'chat:chat' %}">
                        <div class="col-sm-2 col-xs-2 heading-compose  pull-right">
                            <i class="fa fa-comments fa-2x  pull-right" aria-hidden="true"></i>
                        </div>
                    </a>
                </div>
                <div class="row searchBox">
                    <div class="col-sm-12 searchBox-inner">
                        <div class="form-group has-feedback">
                            <form action="{% url 'friend:search_friend' %}" method="get" name="search_friend"
                                  id="searchForm">
                                <input id="searchText" type="text" class="form-control" name="nickname" placeholder="Search" required>
                            </form>
                            {#                            <span class="glyphicon glyphicon-search form-control-feedback"></span>#}
                        </div>
                    </div>
                </div>

                <div id="rowSideBar" class="row sideBar">
                    {% for friend in user_friends %}
                        <a href="{% url 'chat:room' friend.username %}" class="LinkFriend">
                            <div class="row sideBar-body">
                                <div class="col-sm-3 col-xs-3 sideBar-avatar">
                                    <div class="avatar-icon">
                                        <img src="{{ friend.avatar.url }}">
                                    </div>
                                </div>
                                <div class="col-sm-9 col-xs-9 sideBar-main">
                                    <div class="row">
                                        <div class="col-sm-8 col-xs-8 sideBar-name">
                                            <span class="name-meta">{{ friend.username }}</span>
                                        </div>
                                        <div class="col-sm-4 col-xs-4 pull-right sideBar-time">
                                            {% if friend.pk != other_user.pk %}
                                                <span class="time-meta pull-right" id="{{ friend.username }}">{% if friend.unread_msgs %}{{ friend.unread_msgs }}{% endif %}</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-8 conversation">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</div>
<div class="Data" data-username="{{ user.username }}"></div>
{% block script %}
{% endblock script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/hogan.js/3.0.2/hogan.min.js"></script>
<script src="{% static 'js/notifications.js' %}"></script>
<script src="{% static 'js/ajax_search.js' %}"></script>
</body>
</html>

templates/chat/chat.html
{% extends './base.html' %}
{% load static %}
{% block content %}
    <h2 class="text-center text-muted text-dark">Виберіть, кому хочете написати...</h2>
{% endblock content %}
{% block script %}
{% endblock script %}

templates/chat/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Simple Web Chat</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
  <div class="container">
    <h1>SWC - Simple Web Chat</h1>
    <div class="buttons">
      <a class="button" href="{% url 'chat:login' %}">Увійти</a>
      <a class="button" href="{% url 'chat:register' %}">Зареєструватись</a>
    </div>
  </div>
</body>
</html>

templates/chat/room.html
{% extends './base.html' %}
{% load static %}
{% block content %}
    <div class="row heading">
        <div class="col-sm-2 col-md-1 col-xs-3 heading-avatar">
            <div class="heading-avatar-icon">
                <img src="{{ other_user.avatar.url }}">
            </div>
        </div>
        <div class="col-sm-8 col-xs-7 heading-name">
            <a class="heading-name-meta">{{ other_user.username }}</a>
            <span class="heading-online" data-url="{% url 'chat:user_status' other_user.pk %}"
                  data-friend_pk="{{ other_user.pk }}"></span>
        </div>
        <div class="col-sm-1 col-xs-1  heading-dot pull-right">
            <i class="fa fa-ellipsis-v fa-2x  pull-right" aria-hidden="true"></i>
        </div>
    </div>

    <div class="row message" id="conversation">
    </div>

    <div class="row reply">
        <div class="col-sm-1 col-xs-1 reply-emojis">
            <i class="fa fa-smile-o fa-2x"></i>
        </div>
        <div class="col-sm-9 col-xs-9 reply-main">
            <textarea class="form-control" rows="1" id="comment"></textarea>
        </div>
        <div class="col-sm-1 col-xs-1 reply-recording">
            <i class="fa fa-microphone fa-2x" aria-hidden="true"></i>
        </div>
        <div class="col-sm-1 col-xs-1 reply-send">
            <i id="chat-message-submit" class="fa fa-send fa-2x" aria-hidden="true"></i>
        </div>
    </div>
{% endblock content %}
{% block script %}
    <div class="Data-rn" data-room_name="{{ room_name }}"></div>
    <div class="Data-fui" data-from_user_id="{{ user.pk }}"></div>
    <div class="Data-tui" data-to_user_id="{{ other_user.pk }}"></div>
    <script src="{% static 'js/room.js' %}"></script>
    <script src="{% static 'js/user_status.js' %}"></script>
    <script src="{% static 'js/typing.js' %}"></script>
{% endblock script %}